### ISSUE TITLE
crash when used in colab

### ISSUE THREAD

**Issue by toinnn** [mCodingLLC/VideosSampleCode#11]
i forked your "77 metaclasses in Python/overloading.py" to use in a project and found that even though it works normally on my local machine but it crashes in a googlecolab when used

**Comment by mCodingLLC** [comment]
It would be difficult to provide any help since you didn't provide any error output or logs, but most errors people report in this repo are just from using an out-of-date version of Python (typically resulting in an ImportError or AttributeError when trying to use a new feature). I believe colab runs Python 3.7 by default, which is now 4ish years old. Try upgrading your colab instance to a more recent version of Python. I don't recall exactly what I used but it would not surprise me if 3.8 or 3.9 was required for that overloading demo. Or, depending on the error, it might be an easy fix in 3.7. Note, however, that if you are using colab for tensorflow, tensorflow may not support any other version of Python and you may run into other issues because of that. Hope this helps and best of luck. Please post if you are able to solve the issue.
